PainelEletronicoWeb/Controllers/CadastrosController.cs
using System;
using PainelEletronicoWeb.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web;

namespace PainelEletronicoWeb.Controllers
{
    public class CadastrosController : Controller
    {
        [Authorize(Roles = "Superadmin")]
        public ActionResult CamaraMunicipal()
        {
            try
            {
                CamaraMunicipalModel m = new CamaraMunicipalModel();
                var model = m.Listar();
                return View(model);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return PartialView("../Erro");
            }
        }

        [Authorize(Roles = "Superadmin")]
        public ActionResult Vereador(Guid? idCamara)
        {
            try
            {
                HttpContext.Session.Remove("IDCamaraVereador");
                HttpContext.Session.Add("IDCamaraVereador", idCamara);
                VereadorModel m = new VereadorModel();
                var model = m.Listar(idCamara == null ? Guid.Empty : (Guid)idCamara);
                return View(model);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return PartialView("../Erro");
            }
        }

        [Authorize(Roles = "Superadmin,Admin")]
        public ActionResult Votacao()
        {
            try
            {
                VotacaoModel m = new VotacaoModel();
                IEnumerable<VotacaoModel> model = new List<VotacaoModel>();
                if(User.IsInRole("Superadmin"))
                    model = m.Listar();
                else
                    model = m.Listar(CamaraMunicipalModel.ObterID(User.Identity.Name));
                return View(model);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return PartialView("../Erro");
            }
        }
    }
}

PainelEletronicoWeb/Controllers/VereadorController.cs
using System;
using System.Web.Mvc;
using PainelEletronicoWeb.Models;

namespace PainelEletronicoWeb.Controllers
{
    public class VereadorController : Controller
    {
        [Authorize(Roles = "Superadmin")]
        public JsonResult Salvar(VereadorModel model)
        {
            try
            {
                bool suc = model.Salvar();
                return Json(new { sucesso = suc, id = model.ID });
            }
            catch (Exception e)
            {
                return Json(new { sucesso = false, erro = e.Message });
            }
        }

        [Authorize(Roles = "Superadmin")]
        public JsonResult Excluir(VereadorModel model)
        {
            try
            {
                bool suc = model.Excluir();
                return Json(new { sucesso = suc, id = model.ID });
            }
            catch (Exception e)
            {
                return Json(new { sucesso = false, erro = e.Message });
            }
        }
    }
}

PainelEletronicoWeb/Views/Shared/_Layout.cshtml
@using PainelEletronicoWeb.Models
@{
    ViewBag.ApplicationName = "Painel Eletrônico Web";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @ViewBag.ApplicationName</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink((string)ViewBag.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @if (Request.IsAuthenticated)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Cadastros <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Superadmin"))
                                {
                                    <li>@Html.ActionLink("Câmaras Municipais", "CamaraMunicipal", "Cadastros")</li>
                                    <li>@Html.ActionLink("Vereadores", "Vereador", "Cadastros")</li>
                                }
                                <li>@Html.ActionLink("Votações", "Votacao", "Cadastros")</li>
                            </ul>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="javascript:void(0);" onclick="javascript:painel.abrirPainel('@CamaraMunicipalModel.ObterDiretorio(User.Identity.Name)');">Painel</a>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            }
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>